In [5]:
import numpy as np

## Arrays and Vectorization

**Arrays** are sequences of same-type data points (most-often numbers).  Numpy allows us to work with the sequence without writing a for-loop, using a technique called **vectorization**.  

So, instead of writing:

```python
values = [1, 3, 6, 8, 2]
squares = [el ** 2 for value in values]
```

We can instead write:

```python
values = np.array([1, 3, 6, 8, 2])
squares = values ** 2
```

Besides an **array()** class, Numpy also includes a lot of math functions, which makes analysis much easier.  Let's try some out!

## Numpy Exercises

Turn the following list into an array:

```python
my_list = [3, 6, 2, 10]
```

In [22]:
import numpy as np

In [7]:
my_list = np.array([3,6,2,10])

Add 20 to each element of the array [-3, 5, 2].

In [9]:
newar = np.array([-3,5,2])
newar + 20

array([17, 25, 22])

Get the absolute value of all numbers from -6 to 6

In [65]:
absarray = np.arange(-6,7)
abss = np.abs(absarray)
print(abss)

[6 5 4 3 2 1 0 1 2 3 4 5 6]


Get the first 5 values in the array.

In [66]:
abss[:5]

array([6, 5, 4, 3, 2])

Reverse-order the array below.

In [68]:
revar = np.flip(absarray)
revar

array([ 6,  5,  4,  3,  2,  1,  0, -1, -2, -3, -4, -5, -6])

### Building Arrays

Numpy has some convenient array-building functions as well.  Some commonly-used are examples are **arange()**, **linspace()**, **zeros()**, and the random number generation functions in **random**.

Make an array containing the numbers 1 to 15.

In [38]:
numar = np.arange(1,16)
numar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

Make an array containing 20 zeros.

In [39]:
zero = np.zeros(20)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

Make an array contain 20 ones!

In [70]:
zeroone = zero + 1
zeroone
#or
np.ones(20)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

Generate an array of 10 random numbers from Numpy's **random** submodule, using any function you want.

In [44]:
rand = np.random.random(10)
rand
#random.random random is a module within a module (numpy) and random is the fuction within that submodule

array([0.86408492, 0.44651017, 0.29236075, 0.79843356, 0.74521653,
       0.62241454, 0.43027048, 0.17421539, 0.50469034, 0.24655892])

Get the mean of these numbers.

In [71]:
randmean = np.mean(rand)
randmean
#or
rand.mean()

0.5124755604253589

What is the sum of these numbers?

In [49]:
randsum = sum(rand)
randsum

5.124755604253589

The standard deviation?

In [52]:
randstd = np.std(rand)
randstd

0.2272460996603169

Subtract the mean of the array from each element in the array (a.k.a. "mean-centering" the values)

In [53]:
center = rand - randmean
center

array([ 0.35160936, -0.06596539, -0.22011481,  0.285958  ,  0.23274097,
        0.10993898, -0.08220508, -0.33826017, -0.00778522, -0.26591664])

### Slicing Arrays

Slice only the values of the array [1, 5, 3, 8, 7] that are greater than 3.

In [55]:
nar = np.array([1,5,3,8,7])
nar
narg = nar[nar>3]
narg

array([5, 8, 7])

Make an array of boolean values that says which elements of the array [4, 2, 10, 6, 1, 7] are even. (Hint: The result should be [True, True, True, True, False, False])

In [60]:
boolar = np.array([4, 2, 10, 6, 1, 7])
boolar2 = boolar % 2
boolar3 = boolar2 < 1
boolar3

array([ True,  True,  True,  True, False, False])

Make an array that says which elements in the array [4, 2, 10, 6, 1, 7] are equal to 10.

In [62]:
is10 = boolar == 10
is10

array([False, False,  True, False, False, False])

Select only the values from the exercise above that are above the mean.

In [63]:
abovemean = boolar > np.mean(boolar)
abovemean

array([False, False,  True,  True, False,  True])

Multiply all the values in the array [2, 5, 1, 10, 6] by 100, but only if they are less than 6.

In [77]:
bigar = np.array([2,5,1,10,6])
bigar[bigar < 6]*=100
bigar

array([200, 500, 100,  10,   6])

### Translating Algorithms into Code

Calculate the standard deviation of an array's values, without using the numpy.std() function.  (Formula can be found here: http://www.mathsisfun.com/data/standard-deviation-formulas.html)

1. Work out the Mean (the simple average of the numbers)
2. Then for each number: subtract the Mean and square the result
3. Then work out the mean of those squared differences.
4. Take the square root of that and we are done!


In [80]:
x = np.random.normal(10, 1, size=1000)
np.sqrt(np.mean((x - np.mean(x)) ** 2))

0.9963504637768734

In [ ]:
def standard_deviation(x):np.sqrt